version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mazdour
      MYSQL_DATABASE: usersdb
      MYSQL_USER: adam
      MYSQL_PASSWORD: adam
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: adam
      DB_PASSWORD: adam
      DB_NAME: usersdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_URL: http://backend:8000
    container_name: frontend-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  tests:
    build:
      context: ./Backend
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: adam
      DB_PASSWORD: adam
      DB_NAME: usersdb
    profiles: ["test"]

volumes:
  mysql-data:
