FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install pytest pytest-cov httpx

CMD ["pytest", "--cov=main", "--cov-report=term", "--cov-report=xml"]